### PR TITLE
fix null pointer

### LINKED ISSUE #35: Blank page when voting and "Receive notification email on activity" flag enabled
If you vote and "Receive notification email on activity" is enabled you get  a blank page.

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #35, @danielepercivaldi please review

### CODE REVIEW

**Comment by v1r0x** [comment]
already fixed in #43

**Comment by danielepercivaldi** [comment]
Hi. Sorry, I couldn't review it. If you merged it into the master, well, I've just tested it and it doesn't work. Again blank page.

**Comment by v1r0x** [comment]
Tested it yesterday and worked well. Are you on current master? If so, please provide your logfiles

**Comment by danielepercivaldi** [comment]
In order to be sure, I've just got the master and tested. This is the log:

cattura

and I've checked pagecontroller.php: it seems to me that there are not the changes you did in fix-blank-page.

**Pull request closed without merging**
