### PR TITLE
add extended anon type

### LINKED ISSUE #100: Anonymous has no effect for polls admin
If I use the Anonymous-mode I've expected that I, as the one who created the poll, couldn't see who voted for what. But the opposite is the case: I can see who voted for what.

Maybe it would be a good idea to have an advanced Anonymous-mode. So no-one could be blamed for its choices.

### PR DESCRIPTION
**Pull request by v1r0x**
Fix #100 Had to create a new branch/pull request. This is an updated version of #106 

Please review @scroom

### CODE REVIEW

**Comment by scroom** [comment]
Should I test master? Or the branch new-full-anon? And it it a problem to test it with Nextcloud? (I no longer have OC installations but could create one if it is a problem)

**Comment by v1r0x** [comment]
Please test new-full-anon. I don't think that this is a problem. I'm using OC and NC and polls works on both machines.

**Comment by scroom** [comment]
Works great! (Just had to change the info.xml to make it run under NC) No more double votes and still anonymity!

**Comment by v1r0x** [comment]
Perfect! Thanks for your help :smiley:

**Pull request merged**
