### PR TITLE
add extended anon type, replace username with random id

### LINKED ISSUE #100: Anonymous has no effect for polls admin
If I use the Anonymous-mode I've expected that I, as the one who created the poll, couldn't see who voted for what. But the opposite is the case: I can see who voted for what.

Maybe it would be a good idea to have an advanced Anonymous-mode. So no-one could be blamed for its choices.

### PR DESCRIPTION
**Pull request by v1r0x**
fix #100 
@scroom what do you think about it? Only problem I see is that users could vote several times since the name is replaced by a random id

### CODE REVIEW

**Comment by scroom** [comment]
Isn't it possible to prevent voting several times (maybe it is sufficient to just hide the username (and maybe replace it by a random number or something else like user1, user2 ....?)

**Comment by v1r0x** [comment]
Was my first idea, but this would give admins still the ability to have a look at the votes in the database. Maybe this is too much _security_?

**Comment by v1r0x** [comment]
What's your opinion? Should double votes be allowed and admin users can not see who voted for what (even in the database) or should double votes be prevented but admins users can still see who voted for what in the database?

**Comment by scroom** [comment]
If you mean with admin, that really just the cloud admin (and not the one who created the poll) can have a look in the database I would prefer to prevent double votes.

**Pull request merged**
