### PR TITLE
replace default params with undefined check

### PR DESCRIPTION
**Pull request by v1r0x**

### CODE REVIEW

**Comment by v1r0x** [comment]
fixes #13

**Comment by danielepercivaldi** [comment]
Thank you for your answer.
Sorry, It does not work yet, in Firefox too.
I reinstalled the original version an now it does not work definitely ... do you think that if the old version 0.6.4 was present before something in database could compromise the functionality of your new version?

**Comment by v1r0x** [comment]
The database layout has changed in the new version. Polls from the old app won't work anymore.
But is the problem with the datepicker fixed?

**Comment by danielepercivaldi** [comment]
Hi.
I know previous polls don't work with new version. I meant if database changes could prevent the new version from working. But it doesn't matter.
I confirm you that datepicker still does not work.

**Comment by v1r0x** [comment]
Sorry, I don't exactly understand what you mean with the database.
Could you please open the developer console in chrome (`ctrl+shift+j`) and (re)load the create/edit page and check if there is an error?

**Comment by danielepercivaldi** [comment]
Hi.
Here the log:
jquery.min.js?v=dc85ac3d3d1a23adb4bb39169baa3a51:6 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Navigated to https://nerv.net.intre.it/index.php/apps/polls/create
create_edit.js?v=dc85ac3d3d1a23adb4bb39169baa3a51:297 Uncaught SyntaxError: Unexpected token =
jquery.min.js?v=dc85ac3d3d1a23adb4bb39169baa3a51:6 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by v1r0x** [comment]
Are you sure that you're on the latest version?
try
```bash
git clone https://github.com/v1r0x/polls.git
cd polls
git checkout fix-default-params
```

**Comment by danielepercivaldi** [comment]
Well, it reads 0.6.9, it's on oc app store ... I'll try to get the one on git.

Thanks.

**Comment by danielepercivaldi** [comment]
Hi.
Ok. It works.
Now only waiting for oc bug correction about https redirect.

Thank you for your support.

**Comment by v1r0x** [comment]
Glad it works now. Don't know if this will be in 8.2.3 and/or 9, but I hope so. If not it is (fortunately) easy to fix it temporary after all.

**Comment by danielepercivaldi** [comment]
Unfortunately not easy for me.
I'm using oc 8.1.5 and file RedirectResponse.php is quite different from the one here https://github.com/owncloud/core/blob/master/tests/lib/appframework/http/RedirectResponseTest.php#L46.
Which version is it referred to? 8.2.x?

**Comment by v1r0x** [comment]
Yes, current master of oc is 8.2.2. But I checked the 8.1.5 release and you have to replace `Http::STATUS_TEMPORARY_REDIRECT` with `Http::STATUS_SEE_OTHER` in `lib/public/appframework/http/redirectresponse` on line 47.

**Comment by danielepercivaldi** [comment]
Something wrong again. Below the console log:
https://nerv.net.intre.it/core/vendor/jquery/jquery.min.js?v=e2dd59b96267903f7a35f4e5c2d57557 Failed to load resource: the server responded with a status of 412 (Precondition failed)send @ jquery.min.js?v=e2dd59b96267903f7a35f4e5c2d57557:6

Internal server error happens when it tries to load the list of polls.

**Comment by v1r0x** [comment]
Please open a new issue and give some more information (especially the js log and oc log). Thanks.

**Comment by danielepercivaldi** [comment]
Hi.
Today I upgraded to oc 8.2.3 and now I'm in trouble cause of redirectresponse.php bug.
The file is different from  https://github.com/owncloud/core/blob/master/tests/lib/appframework/http/RedirectResponseTest.php#L46. It's the same as the one in oc 8.1.5 but the fix you suggested me in this issue does not work, so when I add a poll it returns to polls home and no poll is added.

**Comment by v1r0x** [comment]
The link points to the unit test file. You should edit this one: https://github.com/owncloud/core/blob/v8.2.3/lib/public/appframework/http/redirectresponse.php#L47 (thats the one for 8.2.3)

**Comment by danielepercivaldi** [comment]
Thank you.
Now it's ok.
Ready for next test session!

**Pull request merged**
