### PR TITLE
Design changes proposal #2

### PR DESCRIPTION
**Pull request by v1r0x**
Follow-up of #52

### CODE REVIEW

**Comment by v1r0x** [comment]
@mcorteel Best solution I found with my git skills ;)

**Comment by mcorteel** [comment]
Well, if it works ;)

**Comment by v1r0x** [comment]
So, ready to merge?

**Comment by mcorteel** [comment]
Looks OK to me. I don't have time to test the new colors, but I guess it's OK. You should merge anyway!

**Pull request merged**
