### PR TITLE
Add french translation files

### LINKED ISSUE #108: Translation - FR or IT
Hello, 

Thanks v1r0x for this application.

As this problem : https://github.com/v1r0x/polls/issues/48

I want translate your application in french but i can't...

I have also create fr.json and fr.php but this modification don't work.

[fr.php.txt](https://github.com/v1r0x/polls/files/631452/fr.php.txt)

[fr.json.txt](https://github.com/v1r0x/polls/files/631449/fr.json.txt)

Can you help me please ?

Thanks,

### PR DESCRIPTION
**Pull request by v1r0x**
see #110, fix #108 

Please review @Ludovicis

### CODE REVIEW

**Comment by Ludovicis** [comment]
Thanks v1r0x,

I have test but no french language... Even if i change the name of french file with en.php and en.json in l10n directory. Maybe i have forgetten something

**Comment by v1r0x** [comment]
You have to checkout the `french-trans` branch. Either clone the repo and switch branch
```
cd owncloud-folder/apps

**Comment by Ludovicis** [comment]
Hi v1r0x,
Thanks, i have tried with french-trans branch but no french langauge only english language... I have check my personnal setting set to french language it's ok. I have change my personnal setting from french to english language and come back after to french language; same result...
I have maybe forget something...

**Comment by v1r0x** [comment]
This is weird.
I set my language in the personal settings to Français and reloaded the polls app. This is what it looks like:

french-polls

**Comment by Ludovicis** [comment]
Thanks, but for me no result in firefox (I have erase the cache before) and on google chrome.
Maybe someone can test also... 
How can i check if french language is used in log of the tool devellopment of my navigator ?

**Comment by v1r0x** [comment]
I think @jancborchardt has a french UI. Could you please test this or do you have any idea what could be wrong?

**Comment by Ludovicis** [comment]
If it can help, if i change in personnal setting my language to deutch personlich; i have deutch language in poll application.

**Comment by Ludovicis** [comment]
Hi v1r0x,

Have you find an other french user for test, please ? If you want we can also seen this error together with teamviewer for example ?

Thanks,

**Comment by Ludovicis** [comment]
Hi v1r0X,

my error is "app":"l10n","message":"Failed to load \/var\/www\/nextcloud\/apps\/polls\/l10n\/fr.json - json error code: 3"

Thankq,

**Comment by v1r0x** [comment]
Does this file exist? If so, does it has the correct access rights? Your webserver user should have at least read and write permissions.

**Comment by Ludovicis** [comment]
This file exist in /var/www/nextcloud/apps/polls/l10n/fr.json directory.
Same error with read and write permissions for www-data user (Apache server)

**Comment by v1r0x** [comment]
Have you tried to download the file from github and replace your local file with it?

**Comment by Ludovicis** [comment]
Yes and same result sorry... maybe this file is not the good... maybe can you send  your fr.json and fr.php files by mail ?
Votre branche est à jour avec 'origin/french-trans'.
Your branch is up to date with 'origin / french-trans'.

**Comment by Ludovicis** [comment]
Hi v1r0x,
I have find the solution with my error:
sudo -u www-data php occ l10n:createjs polls fr
Result--> Javascript translation file generated: /var/www/nextcloud/apps/polls/l10n/fr.js
Json translation file generated: /var/www/nextcloud/apps/polls/l10n/fr.json

The solution was simple... It missed the file fr.js generated with the previous command
Maybe now, you can publish this new branch for users with new translation

Thanks,

**Comment by v1r0x** [comment]
Grean news! I'll add the fr.js file to the repo. Then I'll merge this branch. Thanks for your translations and the solution!

**Comment by Ludovicis** [comment]
[fr.zip](https://github.com/v1r0x/polls/files/781719/fr.zip)

**Comment by Ludovicis** [comment]
[fr.zip](https://github.com/v1r0x/polls/files/784609/fr.zip)

**Pull request merged**
