### PR TITLE
Design changes proposal

### PR DESCRIPTION
**Pull request by mcorteel**
This is far from finished, but it contains a lot of improvements and some design proposals.
There is a lot of cleanup work to do and I have introduced some regressions, but I think it's a little user-friendlier!
What do you think?

### CODE REVIEW

**Comment by v1r0x** [comment]
First of all thanks for your work!
There are some great improvements, looks nice!
But as you said, it's not finished and we should adjust some of the changes.
I'll try to cover all things we should polish in a checklist:
- edit/new page
  - [ ] don't expand expire input to whole page
  - [ ] don't expand choice table to whole page
- [ ] poll page
  - [ ] table layout looks bulky, maybe it looks better with two colors (see misc)
  - [ ] comment and share link look a bit cramped. I think it would be better to move it back to the old position
  - [ ] Disable edit functionality in the share entry
  - [ ] I like the share icon and style but I think using "share" and the icon is misleading, because it is not possible to actually share somethink
  - [ ] Replace "Back to polls list" with the old icon and maybe a text (e.g. "Home")
- misc
 - [ ] use two colors for table rows
 - [ ] use old colors (red, green, yellow)
 - [ ] fix user restrictions (`document.getElementById("table_access").style.display is null`)

Beside that: Looks really nice!

**Comment by mcorteel** [comment]
Thanks for your quick reply!
I fixed most of that, but I kept the two-column view for the vote page because it leaves _a lot_ of blank space on larger screens if everything is in one column (and I think it's interesting to have see the comment feed with the votes). But I widened the comments column a little and increased the collapse point to 1000px so that smaller screens still have a one column view (we can tweak that a little more if you want).
I didn't rename the button "Home", because it's a confusing label IMHO, but I added the home icon.
I'm not sure what you mean about user restrictions. I haven't tested the feature yet but it should work in the create/edit page.
There still are some bugs and there's a lot of testing to do, I'm working on it :)
What do you think?

**Comment by v1r0x** [comment]
Can not test it right now. But from what you wrote it sounds promising :)
I'm not completely happy with "Back to polls list". Maybe we should use "Back to Summary" which would be more consistent with the heading on the summary page.
In create/edit mode you can switch between hidden, restricted, etc. but switching between them throws the exception stated in my last comment. Also the select users/groups popup isn't there anymore if you click on "Select...".

I'll test it later or the next days and let you know what I think ;)

**Comment by mcorteel** [comment]
I don't see any exception and the users/groups popup has been replaced by an inline selection. I would ultimately like it to use the standard users/groups selectors (used in the OC administration) but I haven't looked into that yet.
Please tell me if that still doesn't work for you!

**Comment by v1r0x** [comment]
Thanks again!
I'll update the list above. But we (you ;)) are getting closer :)

**Comment by mcorteel** [comment]
Have you tried it with my last changes? Your screenshot isn't up-to-date.
And for the error, there is no such line in the code... There isn't even a reference to `table_access` anywhere in the repository!

**Comment by v1r0x** [comment]
Now it works. Damn cache ;)

**Comment by mcorteel** [comment]
I fixed everything. Can you merge the PR?

**Comment by v1r0x** [comment]
Looks good, but two things:
1. Could you squash some of the commits?
2. Is there a reason you replaced the checkmark and cross icons?

**Comment by mcorteel** [comment]
I squashed all the commits in [this branch](https://github.com/mcorteel/polls/tree/design_changes_squash). Should I create another pull request?
I was planning on changing the cross icon to better match the check one, but I suck at image editing, so I gave up. You can change that back if you want.

**Comment by v1r0x** [comment]
You can squash them in this pr and force push.
Ok, I'll switch back to the old checkmark and cross and maybe we can change them in the future.

**Comment by mcorteel** [comment]
Done!

**Comment by mcorteel** [comment]
@v1r0x any news on this? I'd like to cleanup the code some more, but I'm waiting for this to be merged to have a sane master to branch.

**Comment by v1r0x** [comment]
Sorry, was busy the last days. Will commit and merge later. Sorry for the delay!

**Comment by mcorteel** [comment]
No problem!
I will try to cleanup the code afterward. I think it would be great if this app could reach the stability and security level required for official OC apps! We would get one step closer to sticking it to doodle ;)

**Comment by v1r0x** [comment]
One thing: Could you rebase this branch?

**Comment by mcorteel** [comment]
Done!

**Comment by v1r0x** [comment]
Thanks!
I added my changes but can not push to your repo. Could you add me as contributor?

**Comment by mcorteel** [comment]
But your repo should remain the "official" one. If I wanted to maintain a fork, I wouldn't have made a PR...

**Comment by v1r0x** [comment]
I wanted to push my changes to your repo and then merge it into my repo ;) If I push all the changes to a new branch in my repo I'd have to create a new PR. Would be easier to push it back to yours and then merge it.

**Comment by mcorteel** [comment]
You can merge this PR in another branch (either using github's PR mechanism or by adding my repo as a read-only remote), make your changes and then merge with your local master and push to github.

**Pull request merged**
