### PR TITLE
use user's timezone for datetimes

### LINKED ISSUE #53: Problem with timezone
Hi!

There seems to be a problem with the timezone.

I am able to reproduce the problem with the following steps:

1.) Create a poll and set date/times to let's say 20:00 o'clock:

edf8062c-04d7-11e6-8a73-d00de9e29389

2.) Visit the poll and check date/times:

32208cb6-04d8-11e6-8b32-9ef00b3aaf7d

The apache timezone is set to Europe/Vienna.

If you need more information let me know.

Regards
Richard

### PR DESCRIPTION
**Pull request by v1r0x**
fix #53 
@darootler and @nozof please review.

### CODE REVIEW

**Comment by darootler** [comment]
Hi,

for me this change has no effect. I am only receiving an additional error:

> {polls} Could not find resource file "/owncloud/apps/polls/css/vote.css"

Regards
Richard

**Comment by v1r0x** [comment]
Did you check out this branch and cleared your cache? ctrl+F5 should be enough

**Comment by darootler** [comment]
Okay, after checking out this branch the css error was gone but no change with timezone.

Regards
Richard

**Comment by v1r0x** [comment]
What should be shown instead of `16:00` and what timezone are you in?

**Comment by darootler** [comment]
I am in Eurpoe/Vienna, i hope my screenshots are self explaining:

creation

vote

Regards
Richard

**Comment by v1r0x** [comment]
Could you add this line after Line 30 in `templates/goto.tmpl.php` (https://github.com/v1r0x/polls/blob/fix-timezone/templates/goto.tmpl.php#L30):
```php
echo "timezone is " . $tz . "<br/>";
```
and tell me what is echoed?

**Comment by darootler** [comment]
Hi,

nothing is echoed:

image

Followed by:

> {PHP} Undefined variable: tz at /var/www/owncloud/apps/polls/templates/goto.tmpl.php#31

Regards
Richard

**Comment by v1r0x** [comment]
Could you please check if you are on the correct branch (`fix-timezone`) and have the latest commits? Looks like the fix hasn't been pulled.

**Comment by darootler** [comment]
Sorry, my fault.

If i am logged into owncloud the timzone is Europe/Berlin (wich is the same timezone like Europe/Vienna):

image

If i am not logged into owncloud the timzone is UTC:

Regards
Richard

**Comment by darootler** [comment]
Seems that in /var/www/owncloud/lib/base.php the timezone is set to UTC...

Regards
Richard

**Comment by v1r0x** [comment]
Don't know why they set it to UTC and not the server's default. But I think it would be better to set the correct time on creation not on the voting page. Error in reasoning ;)
Will commit a fix in a few minutes.

**Comment by v1r0x** [comment]
I fixed the timezone for **new** polls. Existing polls will still show the UTC time. Would be great if you could test it, my server is currently broken and on my laptop I f*cked up my linux and only have windows for now.

**Comment by darootler** [comment]
Creating a poll Ends up with HTTP 500, here are the PHP Errors:

PHP Fatal error:  Class 'OCA\\Polls\\Controller\\DateTimeZone' not found in /var/www/owncloud/apps/polls/controller/pagecontroller.php on line 337

{PHP} Class 'OCA\Polls\Controller\DateTimeZone' not found at /var/www/owncloud/apps/polls/controller/pagecontroller.php#337

Regards
Richard

**Comment by v1r0x** [comment]
Namespace should be fixed now. Could you test again?

**Comment by darootler** [comment]
Just tested it with the actual fix-timezone branch, still the same behavior --> 2 hours difference with a new created poll.

Here is a PHP error:

PHP Warning:  The use statement with non-compound name 'DateTime' has no effect in /var/www/owncloud/apps/polls/templates/goto.tmpl.php on line 5

Regards
Richard

**Comment by v1r0x** [comment]
Don't know why I edited the wrong file earlier, but now the code should be ok. At least it works for me on my test machine.
If it still doesn't work for you: What php version do you use?

**Comment by darootler** [comment]
Now if i am creating the poll for 20:00 o'clock:

image

And after the creation the time changed to 22:00 o'clock, if i am logged on to owncloud:

image

If i am not logged onto owncloud the time seems to be fine:

image

I am using PHP 5.5.9.

Regards
Richard

**Comment by v1r0x** [comment]
Are you on the latest version of the branch? The timezone should be set on creation not on loading the voting page.

**Comment by darootler** [comment]
Sorry, again my fault. I just updated the pagecontroller.php. Now the times are correct, no matter if i am logged into owncloud or not.

But since i am using this branch there are no dates visible:

image

Am i doing something wrong?

If it's a bug and you need a new issue let me know.

Thank you!

Regards
Richard

**Comment by v1r0x** [comment]
I forgot to set the correct color for these rows ;) Will fix this after we merged this branch, if your issue has been fixed?

**Comment by darootler** [comment]
I see :-) Yes, this issue seems to be fixed.

Thanky you!

Regards
Richard

**Comment by v1r0x** [comment]
Thanks for your help and testing! :)

**Pull request merged**
