### PR TITLE
fixed some oc function errors

### LINKED ISSUE #49: Multiple errors and problems
Hi,

thank you for developing this app. It's very great and i love it.

Actually it seems that there are multiple problems, here are some error messages:

{PHP} Undefined variable: poll_id at /var/www/owncloud/apps/polls/templates/goto.tmpl.php#75 --> On poll creation

PHP Fatal error:  Call to a member function t() on a non-object in /var/www/owncloud/apps/polls/controller/pagecontroller.php on line 119 --> On poll creation

{PHP} Trying to get property of non-object at /var/www/owncloud/apps/polls/controller/pagecontroller.php#288 --> On poll creation

{PHP} Undefined variable: l at /var/www/owncloud/apps/polls/controller/pagecontroller.php#119 --> On public vote, followed by a HTTP 500

Let me know if you need more information.

Regards

Richard

### PR DESCRIPTION
**Pull request by v1r0x**
fix #49 @darootler could you please test this PR?

### CODE REVIEW

**Comment by darootler** [comment]
Now i am getting the following errors after a vote:

{PHP} Undefined variable: url at /var/www/owncloud/apps/polls/templates/goto.tmpl.php#76

and

PHP Fatal error:  Call to a member function getDisplayName() on a non-object in /var/www/owncloud/apps/polls/controller/pagecontroller.php on line 124

followed by a HTTP 500

Regards
Richard

**Comment by v1r0x** [comment]
I hope I fixed your errors. Please try again.

**Comment by darootler** [comment]
Now polls isnt working anymore :-(

{PHP} syntax error, unexpected '$msg' (T_VARIABLE) at /var/www/owncloud/apps/polls/controller/pagecontroller.php#129

Regards
Richard

**Comment by darootler** [comment]
Okay,

just reviewed the code a few minutes --> A semicolon was missing at line 128.

With that correction no more php errors occur, but the mail notification looks like this:

"Hello Firstname Lastname,

 participated in the poll 'Testpoll for v1r0x'.

To go directly to the poll, you can use this link"

So in the mail body the name of the participant is missing. Firstname and Lastname is correct. I just replaced my real name. We are heading in the right direction :-)

Regards
Richard

**Comment by v1r0x** [comment]
Thanks for the report! Hopefully it is fixed now :)

**Comment by darootler** [comment]
Name of the participant is okay now. 

I just tested all together from scratch and got the following erros on poll creation:

{PHP} Trying to get property of non-object at /var/www/owncloud/apps/polls/controller/pagecontroller.php#300

{PHP} Undefined variable: offset at /var/www/owncloud/apps/polls/db/participationtextmapper.php#82

{PHP} Undefined variable: limit at /var/www/owncloud/apps/polls/db/participationtextmapper.php#82 

Regards
Richard

**Comment by v1r0x** [comment]
Forgot to remove old code. Should work now :)

**Comment by darootler** [comment]
Hi,

the same problems occur in commentmapper.php:

{PHP} Undefined variable: offset at /var/www/owncloud/apps/polls/db/commentmapper.php#77
{PHP} Undefined variable: limit at /var/www/owncloud/apps/polls/db/commentmapper.php#77

And at least my problem with the timezone. If i create a poll and set the time on any date on 20:00 o'clock, then if you visit the poll, you'll see the time 2 hours before (18:00 o'clock). The Apache timezone is set to Europe/Vienna:

image
image


Any suggestions?

Regards
Richard

**Comment by v1r0x** [comment]
I'm aware of the timezone problem, but haven't found the time to find a solution.
The php error should be fixed. I'd suggest to merge this PR (of course if the errors are fixed) and cover the timezone problem in a new issue.

**Comment by darootler** [comment]
Okay, one more PHP error:

{PHP} Undefined variable: limit at /var/www/owncloud/apps/polls/db/participationmapper.php#82

Regards
Richard

**Comment by v1r0x** [comment]
I should check my php logging...Should be fixed now.

**Comment by darootler** [comment]
Didn't face any erros, seems fine now. Should i create a seperate issue for the timezone?

Thank you!

Regards
Richard

**Comment by v1r0x** [comment]
Yes please. Thanks for your help!

**Pull request merged**
