### PR TITLE
Nc 12

### PR DESCRIPTION
**Pull request by joergmschulz**
group function works in NC12, now

### CODE REVIEW

**Comment by v1r0x** [comment]
Thanks for your PR. I try to review it in the next days.

**Comment by jospoortvliet** [comment]
Any status? Would like to use Polls ;-)

**Comment by v1r0x** [comment]
Tomorrow. Hopefully! :wink:

**Comment by v1r0x** [comment]
I think the duplicated code is fine for now. Can work on some cleanup at the conf in a couple of weeks.
Thanks for all your testing and PR @joergmschulz !

**Comment by jospoortvliet** [comment]
whoohoo!!!

**Comment by jospoortvliet** [comment]
If it is in the app store tomorrow I'll tweet it from the Nextcloud accounts :rocket: :boom:

**Comment by v1r0x** [comment]
Should be there 😉

**Comment by joergmschulz** [comment]
Cool, finally, thank you, @v1r0x .
Rests only the NaN error of Safari - this is beyond where I can contribute. Sorry, else I'd do it.
Anyone?

**Comment by v1r0x** [comment]
Going to fix it as soon as I have more time. I'm unfortunately very busy...Will be in 0.7.4 :)

**Pull request merged**
