### PR TITLE
allow anonymous comments

### LINKED ISSUE #62: comment anonymously
Hey,

I created a public poll and distributed the link to some people who do not have access to an owncloud account. However when they tried to add a comment, they were redirected to the owncloud login page.
Is it possible to add a comment anonymously?

Thank you very much,
Sammy

### PR DESCRIPTION
**Pull request by v1r0x**
fix #62 please review @quizilkend

### CODE REVIEW

**Comment by quizilkend** [comment]
Hey,

I don't know how to review. I disabled the polls app, replaced the changed files and enabled the app again.
When I trie to comment anonymously I get the error message:
An error occurred, your comment was not posted...

However the comment shows up when I reload the page.

**Comment by v1r0x** [comment]
The easiest way would be to install it from git and then checkout this branch. But your method should work as well.
Maybe you got the error, because there was some old data in the cache. Could you test again to check if the error still occurs?

**Comment by quizilkend** [comment]
Sorry, I don't know how to clean the cache, I tried maintenance:repair, but the error message persists.

**Comment by v1r0x** [comment]
Ctrl + F5 should be enough to clean the cache (at least for this particular page).
Could you tell me what steps you made until the error appeared?

**Comment by quizilkend** [comment]
Problem still persists.
To reproduce:
- Log in
- go to polls app
- right click existing poll
- select open link in anonymous tab
- try to comment

**Comment by v1r0x** [comment]
I pushed a new commit. Could you please test again?

**Comment by quizilkend** [comment]
Works like a charm now!
Thanks a lot.

**Comment by v1r0x** [comment]
I'm glad it works! Thanks for your help!

**Pull request merged**
